/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimationDemo: typeof import('./../components/learn-others/animation-demo.vue')['default']
    CanvasAnimationDemo: typeof import('./../components/learn-others/canvas-animation-demo.vue')['default']
    CanvasClipDemo: typeof import('./../components/learn-others/canvas-clip-demo.vue')['default']
    CanvasDemo: typeof import('./../components/learn-others/canvas-demo.vue')['default']
    CanvasPhotoBox: typeof import('./../components/learn-others/canvas-photo-box.vue')['default']
    CanvasSaveRestore: typeof import('./../components/learn-others/canvas-save-restore.vue')['default']
    HelloWord: typeof import('./../components/HelloWord.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UnocssDemo: typeof import('./../components/learn-others/unocss-demo.vue')['default']
  }
}
